#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer

    #colorscheme = "jellybeans"
    colorscheme = "gruvbox"
    background = "dark"
    # colorscheme = "onedark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    enable_ale = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "fire"
    # statusline_inactive_separator = "arrow"
    statusline_inactive_separator = "fire"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_display_mode = true
    statusline_unicode_symbols = true
    # guifont = "DejaVuSansMono Nerd Font:h14"
    # NOTE: the value should be a list, and each item is the name of the plugin.
    disabled_plugins = ["fcitx"]

    bootstrap_before = "myconfig#before"
    # bootstrap_after = "config#after"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#python"
format-on-save = 1

[[layers]]
name = "lang#dart"
format-on-save = 1

# Temporarily disabled
#[[layers]]
#name = "lang#latex"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "git"

[[layers]]
name = 'colorscheme'

[[custom_plugins]]
name = 'sbdchd/neoformat'

[[custom_plugins]]
name = "honza/vim-snippets"

[[custom_plugins]]
name = 'dart-lang/dart-vim-plugin'

[[custom_plugins]]
name = 'thosakwe/vim-flutter'

#[[custom_plugins]]
#name = "ryanoasis/vim-devicons"
#[[custom_plugins]]
#name = "hsanson/vim-android" 
# [[layers]]
# name = 'unite'

# [[layers]]
# name = 'VersionControl'


